import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Titlebar from "@/components/Titlebar";
import { getCookie } from "@/app/actions/cookieFetcher.ts";
import { decrypt } from "../app/private/session.ts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function gettingcookie(): Promise<string>  {
  const cookie = await getCookie();
  const dc = await decrypt(cookie);

  return dc?.user_role + "";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await gettingcookie();
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <Titlebar role={cookie}></Titlebar>
    {children}
    </body>
    </html>
  );
}
